# fly.toml app configuration file generated for rent-mobile on 2023-09-15T13:43:20+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rent-mobile"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
